# Generated by Django 5.1.5 on 2026-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0002_studentprofile_age_studentprofile_class_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('topic', models.CharField(max_length=200)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
