# Generated by Django 5.1.5 on 2026-01-24 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0003_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
