# Generated by Django 5.1.5 on 2026-01-24 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0006_examresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MalpracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('LOOKING_AWAY', 'Looking Away from Screen'), ('HEAD_MOVEMENT', 'Abnormal Head Movement'), ('PHONE_DETECTED', 'Mobile Phone Detected'), ('VOICE_DETECTED', 'Voice/Sound Detected')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malpractice.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
