# Generated by Django 5.1.5 on 2026-01-27 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0008_studentprofile_face_encoding_faceverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malpracticelog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='malpracticelog',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='malpracticelog',
            name='snapshot',
            field=models.ImageField(blank=True, help_text='Frame capture at time of detection', null=True, upload_to='malpractice_snapshots/'),
        ),
        migrations.AlterField(
            model_name='malpracticelog',
            name='log_type',
            field=models.CharField(choices=[('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('LOOKING_AWAY', 'Looking Away from Screen'), ('EYE_TRACKING', 'Eyes Off Screen'), ('HEAD_POSE_LEFT', 'Head Turned Left'), ('HEAD_POSE_RIGHT', 'Head Turned Right'), ('HEAD_POSE_UP', 'Head Tilted Up'), ('HEAD_POSE_DOWN', 'Head Tilted Down'), ('PHONE_DETECTED', 'Mobile Phone Detected'), ('VOICE_DETECTED', 'Voice/Sound Detected'), ('TAB_SWITCH', 'Switched Browser Tab'), ('SUSPICIOUS_OBJECT', 'Suspicious Object Detected')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='malpracticelog',
            index=models.Index(fields=['student', 'exam'], name='malpractice_student_5fab36_idx'),
        ),
        migrations.AddIndex(
            model_name='malpracticelog',
            index=models.Index(fields=['severity'], name='malpractice_severit_914c0c_idx'),
        ),
    ]
