# Generated by Django 5.1.5 on 2026-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0010_examresult_admin_comments_examresult_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='video_file',
            field=models.FileField(blank=True, help_text='Full exam video recording', null=True, upload_to='exam_recordings/'),
        ),
    ]
