# Generated by Django 5.1.5 on 2026-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice', '0011_examresult_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
